version: '3.1'

services:
  springboot:
    image: shreyasmc/spring-boot-mongo:$buildnumber
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappbridge 
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
      - mongodbvol:/data/db
    restart: always
    networks:
    - springappbridge
    
volumes:
  mongodbvol:
    external: true
    
networks:
  springappbridge:
    external: true
